# Generated by Django 4.0.1 on 2022-03-18 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_rename_location_user_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='category_id',
            field=models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.categories'),
        ),
    ]
