# Generated by Django 4.0.1 on 2022-03-24 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='category_id',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.RESTRICT, to='ads.categories'),
        ),
    ]
