# Generated by Django 4.0.1 on 2022-03-24 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_alter_ads_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ads.categories'),
        ),
    ]
